services:
  api-dev:
    build:
      context: .
      dockerfile: scripts/Dockerfile
      target: development
    ports:
      - "${API_DEV_PORT}:${APP_INTERNAL_PORT}"
    volumes:
      - .:/app
      - go_modules:/go/pkg/mod
    environment:
      - PORT=${APP_INTERNAL_PORT}
      - APP_ENV=${APP_ENV_DEV}
      - DATABASE_URL=${DATABASE_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_APP_SLUG=${GITHUB_APP_SLUG}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_PRIVATE_KEY_PATH=${GITHUB_PRIVATE_KEY_PATH}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
    profiles:
      - dev
    depends_on:
      - db

  api-prod:
    build:
      context: .
      dockerfile: scripts/Dockerfile
      target: production
      args:
        - ENTRYPOINT_PATH=./cmd/api
    ports:
      - "${API_PROD_PORT}:${APP_INTERNAL_PORT}"
    environment:
      - PORT=${APP_INTERNAL_PORT}
      - APP_ENV=${APP_ENV_PROD}
      - DATABASE_URL=${DATABASE_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_APP_SLUG=${GITHUB_APP_SLUG}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_PRIVATE_KEY_PATH=${GITHUB_PRIVATE_KEY_PATH}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
    profiles:
      - prod
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
    profiles:
      - dev
      - prod

volumes:
  go_modules:
  pg_data: